### ISSUE TITLE
Update PyPI Publishing Workflow to Use PyPI Trusted Publisher Mechanism

### ISSUE THREAD

**Issue by Vicbi** [StanfordSpezi/SpeziDataPipelineTemplate#15]
### Problem

The current workflow for publishing to PyPI uses secrets for authentication, posing security risks due to potential exposure or leakage.

```yaml
- name: Build and publish
  env:
    TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
    TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
  run: |
    hatch build
    hatch publish
```

### Solution

We should update this to use the PyPI trusted publisher mechanism, which will eliminate the need for secrets to be passed into the environment.

### Additional context

@PSchmiedmayer 's original comment:
"We should use the pypip trusted publisher mechanism to ensure that we don't even need a secret passed into the environment here.

I setup the trusted publisher mechanism for the testing instance of pypi and the StanfordSpezi user with the workflow name and setup as described https://docs.pypi.org/trusted-publishers/creating-a-project-through-oidc/ and https://docs.pypi.org/trusted-publishers/using-a-publisher/

If you use the test environment you should be able to publish to the testing environment.
https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment.

The production environment will be named _release_. (EDITED)

It would be cool to see if we can automatically switch between the environments, e.g., for releases like 0.1.0b1 use the test environment and 0.1.0 uses the production environment. I would also need to do a deep-dive how that would be best structured."

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines
